### ISSUE TITLE
Misleading Documentation

### ISSUE THREAD

**Issue by joeldumke** [Wireless-Innovation-Forum/Spectrum-Access-System#770]
The DPA readme file,

Spectrum-Access-System/src/harness/reference_models/dpa/README.md

should be updated to reflect code changes that apparently go back to April 19. In it's current state, it directs people to move_list_example.py, which calls obsolete routines in move_list.py. 

The readme also makes reference to `Dpa.CalcMoveList()` which doesn't exist. That should probably be dpa.ComputeMoveLists().

**Comment by sbdt-google** [comment]
Hi Joel,

Please check the new documentation *under review in PR #776  and at [this link](https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/blob/c51a36fb3d05c964e0aef28ab01f30c81787f49f/src/harness/reference_models/dpa/README.md).

I updated the original NIST documentation, and hope it clarifies things, otherwise let me know your questions.
Serge

**Comment by joeldumke** [comment]
Thank you, Serge! This is much better. 

Joel
