### ISSUE TITLE
test_WINNF_FT_S_FPR: fccIds used in SAS-THs are not whitelisted in SAS UUT before getting FAD from SAS-THs to SAS UUT

### ISSUE THREAD

**Issue by chandanahs** [Wireless-Innovation-Forum/Spectrum-Access-System#799]
test_WINNF_FT_S_FPR tests: 
fccIds used in SAS-THs are not whitelisted in SAS UUT before getting FAD from SAS-THs to SAS UUT

    # SAS Test Harnesses configurations,
    # Following configurations are for two SAS test harnesses
    sas_test_harness_device_1 = json.load(
        open(os.path.join('testcases', 'testdata', 'device_a.json')))
    sas_test_harness_device_1['fccId'] = 'test_fcc_id_1'
    sas_test_harness_device_1['userId'] = 'test_user_id_1'

    sas_test_harness_device_2 = json.load(
        open(os.path.join('testcases', 'testdata', 'device_b.json')))
    sas_test_harness_device_2['fccId'] = 'test_fcc_id_2'
    sas_test_harness_device_2['userId'] = 'test_user_id_2'

    sas_test_harness_device_3 = json.load(
        open(os.path.join('testcases', 'testdata', 'device_c.json')))
    sas_test_harness_device_3['fccId'] = 'test_fcc_id_3'
    sas_test_harness_device_3['userId'] = 'test_user_id_3'

    # Generate Cbsd FAD Records for SAS Test Harness 0
    cbsd_fad_records_sas_test_harness_0 = generateCbsdRecords(
        [sas_test_harness_device_1], [[grant_request_1]])

    # Generate Cbsd FAD Records for SAS Test Harness 1
    cbsd_fad_records_sas_test_harness_1 = generateCbsdRecords(
        [sas_test_harness_device_2, sas_test_harness_device_3],
        [[grant_request_4], [grant_request_6]])

    # Generate SAS Test Harnesses dump records
    dump_records_sas_test_harness_0 = {
        'cbsdRecords': cbsd_fad_records_sas_test_harness_0
    }
    dump_records_sas_test_harness_1 = {
        'cbsdRecords': cbsd_fad_records_sas_test_harness_1
    }

=====================
Is it not necessary to whitelist fccIds used in SAS THs ('test_fcc_id_1', 'test_fcc_id_2' and 'test_fcc_id_3') in SAS UUT before "logging.info('Collecting SAS TH FADs.')" and "logging.info('Step 10: Triggering CPAS.')" in executeSingleMCPIteration?

**Comment by credtech** [comment]
Since it is the responsibility for the sending SAS to provide correct data to the SAS TH, it should not be necessary to whitelist fccIds.

In other words, a SAS TH may assume that CBSD data received in the dump is valid.

**Comment by jcereced** [comment]
Well...we agreed a while back that even thought it's not a requirement  we would not penalize a SUUT for being extra diligent and making sure it's not accepting data it knows not to be valid.  

We made changes on GRA5 for this very same reason:



  # Inserting FCC IDs on SUUT before CPAS so SUUT will know about them
    self._sas_admin.InjectFccId({'fccId': device_c1['fccId']})
    self._sas_admin.InjectFccId({'fccId': device_c2['fccId']})


I would have to check but if the TH on the functional TCs is not doing the same thing (whitelist FCC IDs) we would need to discuss

**Comment by credtech** [comment]
Actually in the case of GRA.5, the devices are also registered to the SAS UUT (in step 3).

In any case, I tend to agree with you that there is no harm in being extra diligent.

**Comment by kate-harrison** [comment]
Javi graciously reminded me that this issue is still open, so I figured I should probably chime in.

I agree with the previous commenters: this is indeed an inconsistency between the test dev policy and our implementation. Anyone whose SAS will experience difficulties as a result of this inconsistency is recommended to help write/review the PR as quickly as possible so that ITS is not blocked by this issue (no reports yet, to my knowledge).

One "elegant" way to fix the problem would be to have the SAS test harness itself call the Admin API to inject the FCC IDs. This could be done each time [new data is loaded into the SAS test harness](https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/blob/master/src/harness/sas_test_harness.py#L262), so that we are always sure that it happens before the SAS UUT receives the data. Since the code is [smart enough](https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/blob/master/src/harness/sas.py#L154) to avoid injecting the same ID twice, this should not incur any significant overhead beyond the theoretical minimum. By changing the behavior of the SAS TH -- rather than the test case code -- we would simultaneously fix all test cases which are affected via a single change, thus reducing the chance for introducing new bugs. There are probably other good ways to solve this problem, but this is the one that came to mind.

**Comment by chandanahs** [comment]
i believe fccIds will be synced from FCC/WinnForum databases in the later stage.

but for testing, as Kate suggested, i have added below small code to inject fccIds by SAS UUT before collecting the dump from peers for FPR/GPR/EPR tests.

Spectrum-Access-System/src/harness/testcases/WINNF_FT_S_MCP_testcase.py:
    # Step 9: load SAS test harnesses and have the main test harness retrieve
    # those FADs for use in the reference models.
    if self.num_peer_sases:
      # Configure SAS Test Harnesses with new FAD information.
      logging.info('Step 9: re-configuring SAS test harnesses.')
      for test_harness, test_harness_data in zip(
          self.sas_test_harness_objects,
          iteration_content['sasTestHarnessData']):
        test_harness.writeFadRecords([test_harness_data['cbsdRecords']])
        logging.info(test_harness_data['cbsdRecords'])

        **for cbsdIndex in range(len(test_harness_data['cbsdRecords'])):
          logging.info('Step 9a: adding PeerSAS fccIds to SAS UUT whitelisted fccIds.' + test_harness_data['cbsdRecords'][cbsdIndex]["registration"]["fccId"])
          self._sas_admin.InjectFccId({'fccId': test_harness_data['cbsdRecords'][cbsdIndex]["registration"]["fccId"]})**
