### ISSUE TITLE
Need some clarification about Table Mountain Quiet Zone co-ordination requirement

### ISSUE THREAD

**Issue by diptivete** [Wireless-Innovation-Forum/Spectrum-Access-System#804]
Hello,

In WG4 SAS Test & Certification spec section 8.14.3.1, for table mountain quiet zone, it is mentioned before Table 8.14-2 (co-ordination area around table mountain quiet zone reference point) that "each channel corresponds to one 10 Mhz freq range. Partial freq range is also considered as one channel."
But in testcase code for test_WINNF_FT_S_QPR_5(), bandwidth used for calculating total interference from CBSD 2/device_2 (Category B CBSD within 38 km of the Table Mountain QZ ) is 5 Mhz for both the grants.

So I would like to clarify if the constraint for considering partial freq range as one channel is used only for determining total number of channels/grants that could be approved for CBSD around table mountain region, but the actual operation frequency range for every approved grant of the CBSD (even though it is partial) should be used for calculating total interference? Is this interpretation correct or am I misinterpreting this requirement?

**Comment by kate-harrison** [comment]
I don't recognize your username; may I ask your name and affiliation?

Your question is best directed to WinnForum's WG1 (requirements) or WG4 (testing); they will be able to give you an official answer. If you find an inconsistency between their answer and the test code, please re-open this issue and we will fix any errors. Until then, I'm going to close this issue since this is not the right forum in which to seek clarifications on the WinnForum requirements and specifications.

**Comment by diptivete** [comment]
Alright, thanks.
I have updated my name & affiliation in the profile now.
