### ISSUE TITLE
InjectZoneData api uses CbsdId instead of CbsdReferenceId

### ISSUE THREAD

**Issue by syandun** [Wireless-Innovation-Forum/Spectrum-Access-System#818]
SIQ, GRA, PCR, FAD and MCP test cases that use the InjectZoneData() api, use the cbsdId that is returned from the registration response and populate the ZoneData object, specifically the PPAInfo.cbsdReferenceId object.

Here a snippet:
`cbsd_ids = self.assertRegistered(devices)
 Add devices 1 and 3 to the cluster list of the PPA
ppa_record['ppaInfo']['cbsdReferenceId'] = [cbsd_ids[0], cbsd_ids[2]]
…
zone_id = self._sas_admin.InjectZoneData({'record': ppa_record})`

The assumption that CbsdId == CbsdReferenceId is not correct.

From this requirement in doc WINNF-TS-0112-V1.5.0:
"R2-SRR-08: The CBSD-ID shall have a one-to-one correspondence with the combination FCC ID + CBSD S/N and may be identical to that combination and may include a suffix"
There is no strict format or guide on how to create a CbsdId, and different SASes can have their own implementation. As long as there is a one-to-one mapping with the fccId+cbsdSerialNumber the requirement is fulfilled. But it's not mandatory that is should be fccId+cbsdSerialNumber and it suggests that suffixes could be added.

WINNF-TS-0016-V1.2.1 has no definition on how to build a CbsdId.

On the contrary in doc WINNF-TS-0096-V1.3.0, a cbsdReferenceId has a strict definition:
"$CBSD_REFERENCE_ID is defined as
$FCC_ID + “/” + sha1($SERIAL_NUMBER), the
SHA-1 hash of the device manufacturer serial
number that is unique within the FCC ID
namespace scope. This creates a persistent, unique
mapping from specific device parameters to the
ID."

**Comment by kate-harrison** [comment]
For the testing API, we use the CBSD ID in the cluster list (as defined in our docs). This is one case in which we specifically contradict the SAS-SAS API spec since using the CBSD ID more closely matches the way a SAS will create/receive PPAs for CBSDs it manages.

So I agree with you that CBSD ID != CBSD reference ID, but in this case the API is being used as intended. If you'd like, you could add a clarifying note to [the function's documentation](https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/blob/master/src/harness/sas_interface.py#L277) so that others are not confused in the future. For now I will close this issue since everything is WAI.
